from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


class NBATeam(db.Model):
    __tablename__ = 'nbateams'
    TEAM_ID = db.Column(db.Integer, primary_key=True)
    TEAM_NAME = db.Column(db.String(50), nullable=False)
    TEAM_ABR = db.Column(db.String(50), nullable=False)
    TEAM_NICKNAME = db.Column(db.String(50), nullable=False)
    TEAM_CITY = db.Column(db.String(50), nullable=False)
    TEAM_STATE = db.Column(db.String(50), nullable=False)
    TEAM_YEAR_FOUNDED = db.Column(db.Integer, nullable=False)


class NBAGameLogs(db.Model):
    __tablename__ = 'nbagamelogs'
    CITY = db.Column(db.String(50), nullable=False)
    NICKNAME = db.Column(db.String(50), nullable=False)
    TEAM_ID = db.Column(db.String(50), nullable=False)
    W = db.Column(db.String(50), nullable=False)
    L = db.Column(db.String(50), nullable=False)
    W_HOME = db.Column(db.String(50), nullable=False)
    L_HOME = db.Column(db.String(50), nullable=False)
    W_ROAD = db.Column(db.String(50), nullable=False)
    L_ROAD = db.Column(db.String(50), nullable=False)
    TEAM_TURNOVERS = db.Column(db.String(50), nullable=False)
    TEAM_REBOUNDS = db.Column(db.String(50), nullable=False)
    GP = db.Column(db.String(50), nullable=False)
    GS = db.Column(db.String(50), nullable=False)
    ACTUAL_MINUTES = db.Column(db.String(50), nullable=False)
    ACTUAL_SECONDS = db.Column(db.String(50), nullable=False)
    FG = db.Column(db.String(50), nullable=False)
    FGA = db.Column(db.String(50), nullable=False)
    FG_PCT = db.Column(db.String(50), nullable=False)
    FG3 = db.Column(db.String(50), nullable=False)
    FG3A = db.Column(db.String(50), nullable=False)
    FG3_PCT = db.Column(db.String(50), nullable=False)
    FT = db.Column(db.String(50), nullable=False)
    FTA = db.Column(db.String(50), nullable=False)
    FT_PCT = db.Column(db.String(50), nullable=False)
    OFF_REB = db.Column(db.String(50), nullable=False)
    DEF_REB = db.Column(db.String(50), nullable=False)
    TOT_REB = db.Column(db.String(50), nullable=False)
    AST = db.Column(db.String(50), nullable=False)
    PF = db.Column(db.String(50), nullable=False)
    STL = db.Column(db.String(50), nullable=False)
    TOTAL_TURNOVERS = db.Column(db.String(50), nullable=False)
    BLK = db.Column(db.String(50), nullable=False)
    PTS = db.Column(db.String(50), nullable=False)
    AVG_REB = db.Column(db.String(50), nullable=False)
    AVG_PTS = db.Column(db.String(50), nullable=False)
    DQ = db.Column(db.String(50), nullable=False)
    OFFENSIVE_EFFICIENCY = db.Column(db.String(50), nullable=False)
    SCORING_MARGIN = db.Column(db.String(50), nullable=False)
    SEASON = db.Column(db.String(50), nullable=False)
    GAME_DATE = db.Column(db.String(50), nullable=False)
    GAME_ID = db.Column(db.String(50), nullable=False)
    HOME_FLAG = db.Column(db.String(50), nullable=False)
    AWAY_FLAG = db.Column(db.String(50), nullable=False)
    HOME_WIN_PCTG = db.Column(db.String(50), nullable=False)
    AWAY_WIN_PCTG = db.Column(db.String(50), nullable=False)
    TOTAL_WIN_PCTG = db.Column(db.String(50), nullable=False)
    ROLLING_SCORING_MARGIN = db.Column(db.String(50), nullable=False)
    ROLLING_OE = db.Column(db.String(50), nullable=False)
    NUM_REST_DAYS = db.Column(db.String(50), nullable=False)
    TEAM_NAME = db.Column(db.String(50), nullable=False)
    TEAM_NAME = db.Column(db.String(50), nullable=False)
    TEAM_NAME = db.Column(db.String(50), nullable=False)
    TEAM_NAME = db.Column(db.String(50), nullable=False)
