from UserClass import UserClass

u1 = UserClass("Kade", "Townsend", 21, "ktown", "chicken")
print(u1.get_name())
print(u1.get_age())
print(u1.login("ktown", "chicken"))
print(u1.login("ktown", "chicke"))
print(u1.login("town", "chicken"))
print(u1.login("town", "chicke"))
print(u1.get_username())
u1.change_password("hello")
print(u1.login("ktown", "hello"))
print(u1.login("ktown", "chicken"))
print(u1.get_history())
u1.add_bet("win", "1")
print(u1.get_history())