"""Removed jersey number

Revision ID: 6f4abc9269ae
Revises: 8abf4da84fa8
Create Date: 2025-03-28 18:19:17.834524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f4abc9269ae'
down_revision = '8abf4da84fa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfl_player', schema=None) as batch_op:
        batch_op.drop_column('JERSEY_NUMBER')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfl_player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('JERSEY_NUMBER', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
