"""Please migrate

Revision ID: 8abf4da84fa8
Revises: 
Create Date: 2025-03-28 18:14:39.382287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8abf4da84fa8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfl_player', schema=None) as batch_op:
        batch_op.alter_column('PLAYER_ID',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=25),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfl_player', schema=None) as batch_op:
        batch_op.alter_column('PLAYER_ID',
               existing_type=sa.String(length=25),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
