"""Added NBA models

Revision ID: 946e37b7649c
Revises: 6f4abc9269ae
Create Date: 2025-04-07 17:06:55.055178

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '946e37b7649c'
down_revision = '6f4abc9269ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nfl_player')
    op.drop_table('user')
    op.drop_table('nfl_team')
    op.drop_table('nfl_qb_weekly_stats')
    with op.batch_alter_table('nbagameids', schema=None) as batch_op:
        batch_op.alter_column('GAME_ID',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('GAME_DATE',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('HOME_TEAM_ID',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('AWAY_TEAM_ID',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.create_foreign_key(None, 'nbateams', ['AWAY_TEAM_ID'], ['TEAM_ID'])
        batch_op.create_foreign_key(None, 'nbateams', ['HOME_TEAM_ID'], ['TEAM_ID'])

    with op.batch_alter_table('nbagamelogs', schema=None) as batch_op:
        batch_op.alter_column('CITY',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('NICKNAME',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('TEAM_ID',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('W',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('L',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('W_HOME',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('L_HOME',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('W_ROAD',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('L_ROAD',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('TEAM_TURNOVERS',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('TEAM_REBOUNDS',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('GP',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('GS',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('ACTUAL_MINUTES',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('ACTUAL_SECONDS',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('FG',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('FGA',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('FG_PCT',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('FG3',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('FG3A',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('FG3_PCT',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('FT',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('FTA',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('FT_PCT',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('OFF_REB',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('DEF_REB',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('TOT_REB',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('AST',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('PF',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('STL',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('TOTAL_TURNOVERS',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('BLK',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('PTS',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('AVG_REB',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('AVG_PTS',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('DQ',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('OFFENSIVE_EFFICIENCY',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('SCORING_MARGIN',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('SEASON',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('GAME_DATE',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('GAME_ID',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('HOME_FLAG',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('AWAY_FLAG',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('HOME_WIN_PCTG',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('AWAY_WIN_PCTG',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('TOTAL_WIN_PCTG',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('ROLLING_SCORING_MARGIN',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('ROLLING_OE',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('NUM_REST_DAYS',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.create_foreign_key(None, 'nbagameids', ['GAME_ID'], ['GAME_ID'])
        batch_op.create_foreign_key(None, 'nbateams', ['TEAM_ID'], ['TEAM_ID'])

    with op.batch_alter_table('nbapred', schema=None) as batch_op:
        batch_op.alter_column('SEASON',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('GAME_ID',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('GAME_DATE',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('HOME_W',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('HOME_W_PRED',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('AWAY_W_PROB',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('HOME_W_PROB',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.create_foreign_key(None, 'nbagamelogs', ['GAME_ID'], ['GAME_ID'])

    with op.batch_alter_table('nbateams', schema=None) as batch_op:
        batch_op.alter_column('TEAM_ID',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('TEAM_NAME',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('TEAM_ABR',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('TEAM_NICKNAME',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('TEAM_CITY',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('TEAM_STATE',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('TEAM_YEAR_FOUNDED',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nbateams', schema=None) as batch_op:
        batch_op.alter_column('TEAM_YEAR_FOUNDED',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('TEAM_STATE',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('TEAM_CITY',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('TEAM_NICKNAME',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('TEAM_ABR',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('TEAM_NAME',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('TEAM_ID',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('nbapred', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('HOME_W_PROB',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('AWAY_W_PROB',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('HOME_W_PRED',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('HOME_W',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('GAME_DATE',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('GAME_ID',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('SEASON',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('nbagamelogs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('NUM_REST_DAYS',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('ROLLING_OE',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('ROLLING_SCORING_MARGIN',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('TOTAL_WIN_PCTG',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('AWAY_WIN_PCTG',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('HOME_WIN_PCTG',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('AWAY_FLAG',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('HOME_FLAG',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('GAME_ID',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('GAME_DATE',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('SEASON',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('SCORING_MARGIN',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('OFFENSIVE_EFFICIENCY',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('DQ',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('AVG_PTS',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('AVG_REB',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('PTS',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('BLK',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('TOTAL_TURNOVERS',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('STL',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('PF',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('AST',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('TOT_REB',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('DEF_REB',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('OFF_REB',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('FT_PCT',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('FTA',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('FT',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('FG3_PCT',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('FG3A',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('FG3',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('FG_PCT',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('FGA',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('FG',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('ACTUAL_SECONDS',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('ACTUAL_MINUTES',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('GS',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('GP',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('TEAM_REBOUNDS',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('TEAM_TURNOVERS',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('L_ROAD',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('W_ROAD',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('L_HOME',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('W_HOME',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('L',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('W',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('TEAM_ID',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('NICKNAME',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('CITY',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('nbagameids', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('AWAY_TEAM_ID',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('HOME_TEAM_ID',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('GAME_DATE',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('GAME_ID',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)

    op.create_table('nfl_qb_weekly_stats',
    sa.Column('STAT_ID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('PLAYER_ID', sa.VARCHAR(length=25), autoincrement=False, nullable=False),
    sa.Column('PLAYER_NAME', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('PLAYER_ABBR', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('GAME_ID', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('WEEK', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('RECENT_TEAM', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('OPPONENT_TEAM', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('SEASON', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('SEASON_TYPE', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('POSITION', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('HEADSHOT_URL', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('COMPLETIONS', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ATTEMPTS', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PASSING_YARDS', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PASSING_TDS', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('INTERCEPTIONS', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('SACKS', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('SACK_YARDS', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('SACK_FUMBLES', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('SACK_FUMBLES_LOST', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PASSING_AIR_YARDS', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('PASSING_YARDS_AFTER_CATCH', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('PASSING_FIRST_DOWNS', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PASSING_EPA', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('PASSING_2PT_CONVERSIONS', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PACR', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('DAKOTA', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('CARRIES', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('RUSHING_YARDS', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('RUSHING_TDS', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('RUSHING_FUMBLES', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('RUSHING_FUMBLES_LOST', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('RUSHING_FIRST_DOWNS', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('RUSHING_EPA', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('SPECIAL_TEAMS_TDS', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('FANTASY_POINTS', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('FANTASY_POINTS_PPR', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('PASSING_DROPS', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PASSING_DROP_PCT', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('PASSING_BAD_THROWS', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PASSING_BAD_THROW_PCT', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('TIMES_SACKED', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('TIMES_BLITZED', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('TIMES_HURRIED', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('TIMES_HIT', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('TIMES_PRESSURED', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('TIMES_PRESSURED_PCT', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('RUSHING_YARDS_BEFORE_CONTACT', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('RUSHING_YARDS_BEFORE_CONTACT_AVG', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('RUSHING_YARDS_AFTER_CONTACT', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('RUSHING_YARDS_AFTER_CONTACT_AVG', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('RUSHING_BROKEN_TACKLES', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('OFFENSE_SNAPS', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('OFFENSE_PCT', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('PLAYER_POSITION', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('AVG_TIME_TO_THROW', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('AVG_COMPLETED_AIR_YARDS', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('AVG_INTENDED_AIR_YARDS', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('AVG_AIR_YARDS_DIFFERENTIAL', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('AGGRESSIVENESS', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('MAX_COMPLETED_AIR_DISTANCE', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('AVG_AIR_YARDS_TO_STICKS', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('PASSER_RATING', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('COMPLETION_PERCENTAGE', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('EXPECTED_COMPLETION_PERCENTAGE', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('COMPLETION_PERCENTAGE_ABOVE_EXPECTATION', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('AVG_AIR_DISTANCE', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('MAX_AIR_DISTANCE', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['PLAYER_ID'], ['nfl_player.PLAYER_ID'], name='nfl_qb_weekly_stats_PLAYER_ID_fkey'),
    sa.PrimaryKeyConstraint('STAT_ID', name='nfl_qb_weekly_stats_pkey')
    )
    op.create_table('nfl_team',
    sa.Column('TEAM_ID', sa.INTEGER(), server_default=sa.text('nextval(\'"nfl_team_TEAM_ID_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('TEAM_NAME', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('TEAM_ABR', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('TEAM_NICKNAME', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('TEAM_CONF', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('TEAM_DIVISION', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('TEAM_LOGO', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('TEAM_WORDMARK', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('TEAM_ID', name='nfl_team_pkey'),
    sa.UniqueConstraint('TEAM_ABR', name='nfl_team_TEAM_ABR_key'),
    sa.UniqueConstraint('TEAM_NAME', name='nfl_team_TEAM_NAME_key'),
    sa.UniqueConstraint('TEAM_NICKNAME', name='nfl_team_TEAM_NICKNAME_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key'),
    sa.UniqueConstraint('username', name='user_username_key')
    )
    op.create_table('nfl_player',
    sa.Column('PLAYER_ID', sa.VARCHAR(length=25), server_default=sa.text('nextval(\'"nfl_player_PLAYER_ID_seq"\'::regclass)'), autoincrement=False, nullable=False),
    sa.Column('TEAM_ID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('SEASON', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('PLAYER_NAME', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('FIRST_NAME', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('LAST_NAME', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('POSITION', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('STATUS', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('GAME_TYPE', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['TEAM_ID'], ['nfl_team.TEAM_ID'], name='nfl_player_TEAM_ID_fkey'),
    sa.PrimaryKeyConstraint('PLAYER_ID', name='nfl_player_pkey')
    )
    # ### end Alembic commands ###
