import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> f8f41c148148be63db8269515895cad2be595b51
/**
 * Load Google Fonts using Next.Js for optimization. 
 * Geist Sans and Geist Mono are used for styling.
 */
<<<<<<< HEAD
=======
>>>>>>> bae9ee246ac9055185ff74bd2a5b692fadc0c7e9
=======
>>>>>>> f8f41c148148be63db8269515895cad2be595b51
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

<<<<<<< HEAD
<<<<<<< HEAD
/**
 * Metadata for the application, defining title and description.
 */
=======
>>>>>>> bae9ee246ac9055185ff74bd2a5b692fadc0c7e9
=======
/**
 * Metadata for the application, defining title and description.
 */
>>>>>>> f8f41c148148be63db8269515895cad2be595b51
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> f8f41c148148be63db8269515895cad2be595b51

/**
 * Root layout component wrapping the entire application.
 * Applies global fonts and ensures proper document structure
 * @param {object} props - Component props 
 * @param {React.ReactNode} props.children - Nested components to be rendered inside the layout.  
 */
<<<<<<< HEAD
=======
>>>>>>> bae9ee246ac9055185ff74bd2a5b692fadc0c7e9
=======
>>>>>>> f8f41c148148be63db8269515895cad2be595b51
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
